import type { FoundryApiRoute } from "./foundry-domain";

export const FOUNDRY_API_ROUTES: readonly FoundryApiRoute[] = [
  {
    resource: "workspaces",
    path: "/api/foundry/workspaces",
    methods: ["GET", "POST", "PATCH"],
    requiresAuth: true,
    seedable: true,
  },
  {
    resource: "applications",
    path: "/api/foundry/applications",
    methods: ["GET", "POST", "PATCH", "DELETE"],
    requiresAuth: true,
    seedable: true,
    actions: ["archive", "publish-metadata"],
  },
  {
    resource: "pages",
    path: "/api/foundry/pages",
    methods: ["GET", "POST", "PATCH", "DELETE"],
    requiresAuth: true,
    seedable: true,
    actions: ["reorder", "set-home"],
  },
  {
    resource: "widgets",
    path: "/api/foundry/widgets",
    methods: ["GET", "POST", "PATCH", "DELETE"],
    requiresAuth: true,
    seedable: true,
    actions: ["move", "resize", "bind-property"],
  },
  {
    resource: "datasources",
    path: "/api/foundry/datasources",
    methods: ["GET", "POST", "PATCH", "DELETE"],
    requiresAuth: true,
    seedable: true,
    actions: ["test-connection", "introspect-schema"],
  },
  {
    resource: "queries",
    path: "/api/foundry/queries",
    methods: ["GET", "POST", "PATCH", "DELETE"],
    requiresAuth: true,
    seedable: true,
    actions: ["execute", "preview"],
  },
  {
    resource: "javascript-objects",
    path: "/api/foundry/javascript-objects",
    methods: ["GET", "POST", "PATCH", "DELETE"],
    requiresAuth: true,
    seedable: true,
    actions: ["invoke", "lint"],
  },
  {
    resource: "bindings",
    path: "/api/foundry/bindings",
    methods: ["GET", "POST", "PATCH", "DELETE"],
    requiresAuth: true,
    seedable: true,
    actions: ["evaluate"],
  },
  {
    resource: "branches",
    path: "/api/foundry/branches",
    methods: ["GET", "POST", "PATCH"],
    requiresAuth: true,
    seedable: true,
    actions: ["create-branch", "compare", "merge", "restore"],
  },
  {
    resource: "deployments",
    path: "/api/foundry/deployments",
    methods: ["GET", "POST", "PATCH"],
    requiresAuth: true,
    seedable: true,
    actions: ["publish", "rollback", "promote"],
  },
  {
    resource: "permissions",
    path: "/api/foundry/permissions",
    methods: ["GET", "POST", "PATCH", "DELETE"],
    requiresAuth: true,
    seedable: true,
    actions: ["grant", "revoke"],
  },
  {
    resource: "publish-metadata",
    path: "/api/foundry/publish-metadata",
    methods: ["GET", "POST", "PATCH"],
    requiresAuth: true,
    seedable: true,
    actions: ["share", "runtime-bootstrap"],
  },
  {
    resource: "custom-widgets",
    path: "/api/foundry/custom-widgets",
    methods: ["GET", "POST", "PATCH", "DELETE"],
    requiresAuth: true,
    seedable: true,
    actions: ["register", "runtime-entry"],
  },
];
