import type { SwitchboardApiRoute } from "./switchboard-domain";
import { SWITCHBOARD_WEBHOOK_EVENTS } from "./switchboard-constants";

export const SWITCHBOARD_API_ROUTES: readonly SwitchboardApiRoute[] = [
  {
    resource: "accounts",
    path: "/api/switchboard/accounts",
    methods: ["GET", "POST", "PATCH"],
    requiresAuth: true,
    seedable: true,
  },
  {
    resource: "users",
    path: "/api/switchboard/users",
    methods: ["GET", "POST", "PATCH"],
    requiresAuth: true,
    seedable: true,
  },
  {
    resource: "inboxes",
    path: "/api/switchboard/inboxes",
    methods: ["GET", "POST", "PATCH", "DELETE"],
    requiresAuth: true,
    seedable: true,
  },
  {
    resource: "channels",
    path: "/api/switchboard/channels",
    methods: ["GET", "POST", "PATCH", "DELETE"],
    requiresAuth: true,
    seedable: true,
  },
  {
    resource: "contacts",
    path: "/api/switchboard/contacts",
    methods: ["GET", "POST", "PATCH", "DELETE"],
    requiresAuth: true,
    seedable: true,
  },
  {
    resource: "conversations",
    path: "/api/switchboard/conversations",
    methods: ["GET", "POST", "PATCH"],
    requiresAuth: true,
    seedable: true,
    actions: ["assign", "snooze", "resolve", "reopen"],
  },
  {
    resource: "messages",
    path: "/api/switchboard/messages",
    methods: ["GET", "POST"],
    requiresAuth: true,
    seedable: true,
    actions: ["reply", "private-note"],
  },
  {
    resource: "assignments",
    path: "/api/switchboard/assignments",
    methods: ["GET", "POST", "PATCH"],
    requiresAuth: true,
    seedable: true,
  },
  {
    resource: "teams",
    path: "/api/switchboard/teams",
    methods: ["GET", "POST", "PATCH", "DELETE"],
    requiresAuth: true,
    seedable: true,
  },
  {
    resource: "notes",
    path: "/api/switchboard/notes",
    methods: ["GET", "POST", "PATCH", "DELETE"],
    requiresAuth: true,
    seedable: true,
  },
  {
    resource: "labels",
    path: "/api/switchboard/labels",
    methods: ["GET", "POST", "PATCH", "DELETE"],
    requiresAuth: true,
    seedable: true,
  },
  {
    resource: "canned-responses",
    path: "/api/switchboard/canned-responses",
    methods: ["GET", "POST", "PATCH", "DELETE"],
    requiresAuth: true,
    seedable: true,
  },
  {
    resource: "macros",
    path: "/api/switchboard/macros",
    methods: ["GET", "POST", "PATCH", "DELETE"],
    requiresAuth: true,
    seedable: true,
  },
  {
    resource: "automation-rules",
    path: "/api/switchboard/automation-rules",
    methods: ["GET", "POST", "PATCH", "DELETE"],
    requiresAuth: true,
    seedable: true,
  },
  {
    resource: "reports",
    path: "/api/switchboard/reports",
    methods: ["GET", "POST"],
    requiresAuth: true,
    seedable: true,
  },
  {
    resource: "webhooks",
    path: "/api/switchboard/webhooks",
    methods: ["GET", "POST", "PATCH", "DELETE"],
    requiresAuth: false,
    seedable: false,
    events: [...SWITCHBOARD_WEBHOOK_EVENTS],
  },
];
